//
//  FDHomeInteractor.swift
//  FoodDevlivery
//
//  Created ACE_xW on 19/10/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by ACE_xW
//

import UIKit

class FDHomeInteractor: FDHomeInteractorProtocol {
    var fetchedMenu: [FDMenuResponseEntity.Menu] = []
    
    weak var presenter: FDHomePresenterProtocol?
    
    func fetchMenu() {
        FDNetworkingService.shared().fetchMenu { (result) in
            if result.success, let menus = result.responseData as? FDMenuResponseEntity, let menu = menus.menu {
                self.presenter?.onMenuFetched( menu.map { FDHomeMenuEntity($0) } )
            }
        }
    }
    
    func fetchBanners() {
        FDNetworkingService.shared().fetchBanner { (result) in
            if result.success {
                self.presenter?.onBannerFetched(result.responseData as! FDBannerResponseEntity)
            }
        }
    }
}
