//
//  FDHomeRouter.swift
//  FoodDevlivery
//
//  Created ACE_xW on 19/10/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by ACE_xW
//

import UIKit

class FDHomeRouter: FDHomeWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FDHomeViewController(nibName: nil, bundle: nil)
        let interactor = FDHomeInteractor()
        let router = FDHomeRouter()
        let presenter = FDHomePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func navigateToCart() {
        let cartViewController = FDCartRouter.createModule()
        self.viewController?.navigationController?.pushViewController(cartViewController, animated: true)
//        if let viewController =
    }
}
