//
//  FDCartInteractor.swift
//  FoodDevlivery
//
//  Created ACE_xW on 19/10/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by ACE_xW
//

import UIKit

class FDCartInteractor: FDCartInteractorProtocol {
    weak var presenter: FDCartPresenterProtocol?
    
    func fetchCartItems() {
    
    }
}
